#!/usr/bin/env zsh

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Installing Oh My Zsh"
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  successfully open https://github.com/account/ssh

echo "Fixing permissions ..."
  successfully sudo chown -R `whoami` /usr/local

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

echo "Putting Homebrew location earlier in PATH ..."
  successfully echo "
# recommended by brew doctor
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin'" >> ~/.zshrc
  successfully source ~/.zshrc

echo "Installing GNU Compiler Collection and dependencies ..."
  successfully brew tap homebrew/dupes
  successfully brew install autoconf automake apple-gcc42

echo "Installing libksba, recommended for Ruby 1.9.3 ..."
  successfully brew install libksba

echo "Installing ack, for searching the contents of files ..."
  successfully brew install ack

echo "Installing ctags, for indexing files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

echo "Installing ImageMagick, for cropping and re-sizing images ..."
  successfully brew install imagemagick

# Ruby 

echo "Installing RVM (Ruby Version Manager) and Ruby 1.9.3-p327, which becomes the default ..."
  successfully curl -L https://get.rvm.io | bash -s stable --ruby
  successfully echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'
PATH='$HOME/.rvm/bin:\$PATH'" >> ~/.zshrc
  successfully source ~/.rvm/scripts/rvm

echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler rails pg foreman thin --no-rdoc --no-ri

# Heroku

echo "Installing standalone Heroku CLI client. You'll need administrative rights on your machine ..."
  successfully curl -s https://toolbelt.heroku.com/install.sh | sh

echo "Adding Heroku CLI to path"
  successfully echo "
# Heroku CLI
export PATH='/usr/local/heroku/bin:\$PATH'" >> ~/.zshrc
  successfully source ~/.zshrc

echo "Installing the heroku-config plugin for pulling config variables locally to be used as ENV variables ..."
  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/ddollar/heroku-config.git

# Nginx + Pow
# http://www.jamesbadger.ca/2012/03/20/run-nginx-and-pow-on-your-mac/

echo "Installing Pow. You'll need administrative rights"
  successfully echo "export POW_DST_PORT=19999" >> ~/.powconfig
  successfully curl get.pow.cx | sh

echo "Installing Powder"
  successfully gem install powder --no-rdoc --no-ri

echo 'Create dev dir'
  successfully mkdir ~/Development

echo "Installing Nginx"
  successfully brew install nginx

echo "Installing nginx config"
  successfully zsh < <(curl -s https://raw.github.com/TheGiftsProject/laptop/master/nginx)

echo "Run Nginx"
  successfully sudo nginx

# MySQL
# http://madebyhoundstooth.com/blog/install-mysql-on-mountain-lion-with-homebrew/

echo 'Installing MySQL'
  successfully brew install mysql
  successfully source ~/.zshrc

echo 'Configuring MySQL to launch on startup'
  successfully ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
  successfully launchctl load ~/Library/LaunchAgents/hombrew.mxcl.mysql.plist
  successfully unset TMPDIR
  successfully mysql_install_db --verbose --user=`whoami` --basedir="$(brew --prefix mysql)" --datadir=/usr/local/var/mysql --tmpdir=/tmp

echo 'Setting MySQL admin user'
  successfully mysqladmin -u root password 'hello'

echo 'Running MySQL'
  successfully mysql.server start

# Node
echo 'Installind NodeJS'
  successfully brew install node

# Other
echo "Install dot files"
  successfully zsh < <(curl -s https://raw.github.com/TheGiftsProject/laptop/master/dot_files)

echo "Install the EyToolBox"
  successfully gem install engineyard --no-rdoc --no-ri
  successfully git clone git://github.com/yonbergman/EyToolbox.git ~/Development/EyToolbox
  successfully ~/Development/EyToolbox/install.rb
  
  

